name: Compile TypeScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Compile code
        run: yarn tsc

      - name: Test code
        run: yarn test

      # - name: Deploy contract
      #   run: npx hardhat run ./scripts/deploy
